### ISSUE TITLE
Article doesn't have an attributedTo property

### ISSUE THREAD

**Issue by silverpill** [TryGhost/ActivityPub#45]
Example: `https://activitypub.ghost.org/.ghost/activitypub/article/c32ce17a-26ca-4262-ad97-633a2729ae39`

This property is often used to indicate the author of a post.

ActivityPub spec says that `Object.attributedTo` SHOULD be a copy of `Create.actor`: https://www.w3.org/TR/activitypub/#create-activity-outbox.

**Comment by wakest** [comment]
@silverpill Ghost is using @dahlia's Fedify library for their AP stuff so I would assume this bug might really be even more relevant there?

**Comment by dahlia** [comment]
@wakest It should be fixed in the app side!

@allouis We need to add an `attribution` property to `Article` objects:

<https://github.com/TryGhost/ActivityPub/blob/9e9321f7d7a097bd9b16519ab0a0482b0f845025/src/handlers.ts#L67-L75>

**Comment by allouis** [comment]
Fixed here! https://github.com/TryGhost/ActivityPub/commit/7f8bf559942eb4d82b6ac071bd92f965ecc838fd

**Comment by silverpill** [comment]
I can see it, thanks!
