### ISSUE TITLE
Target audience is not specified

### ISSUE THREAD

**Issue by silverpill** [TryGhost/ActivityPub#50]
Example: `https://activitypub.ghost.org/.ghost/activitypub/article/75c9d566-c866-4101-88d0-f294455f79f8`

This `Article` object doesn't have `to` and `cc` properties, which identify entities and actors an object is addressed to. If the article is public, it should be addressed to a special `https://www.w3.org/ns/activitystreams#Public` collection: https://www.w3.org/TR/activitypub/#public-addressing

**Comment by dahlia** [comment]
`Article` objects should have a `to` property here:

<https://github.com/TryGhost/ActivityPub/blob/a2d7ff4fcae111eed13209f6d43841a14d386b8c/src/handlers.ts#L67-L76>
